### ISSUE TITLE
added a public key, got a mail, clicked verify -- keyserver doesn't have it

### ISSUE THREAD

**Issue by hpk42** [mailvelope/keyserver#10]
So i went to https://keys.mailvelope.com, clicked "try it now", uploaded a public key, got a verification link to my mail address (holger at merlinux eu), went to it and it all seemingly worked.  But the keyserver's search does not find it.  I can't add it a second time, it complains that it already has this key.  Is this some temporary sync issue or a real bug?

**Comment by toberndo** [comment]
https://keys.mailvelope.com/pks/lookup?op=get&search=holger%40merlinux.eu seems to work

**Comment by JPAntonisse** [comment]
mailvelope key server does not sync with other key servers. The lookup does not work on the website. (It is on the demo.html page)

**Comment by kylecrawshaw** [comment]
This seems to be causing some confusion with users that I have spoken to. When you attempt to generate a key it uploads it to https://keys.mailvelop.com, but you can't import directly from Mailvelope using that server. Was this a strategic decision or oversight?

**Comment by shuffle2** [comment]
I was able to import OP's public key just fine from https://keys.mailvelope.com using the mailvelope browser plugin (which I might note, is _not_ what this bug tracker is for). @kylecrawshaw maybe you could explain more about what's confusing? It seems to work just fine...  
Or maybe behavior changed between then and now? In which case, the bug is fixed :D

**Comment by toberndo** [comment]
> This seems to be causing some confusion with users that I have spoken to. When you attempt to generate a key it uploads it to https://keys.mailvelop.com, but you can't import directly from Mailvelope using that server. Was this a strategic decision or oversight?

Import from keys.mailvelope.com in the Mailvelope browser extension is now supported.
