### ISSUE TITLE
Verification fails

### ISSUE THREAD

**Issue by crogonint** [mailvelope/keyserver#101]
When I click the link in my verification email (which was sent to my email account which resides in Outlook 365, instead of my Gmail account in the browser, oddly), I get a blank web page that only says:
Invalid request!

I've got no clue how to go about validating either of my email key pairs.
---
Update: In the mailvelope GUI, it says under each key pair that they are valid, but it also says that they haven't been synchronized with the server. I clicked the button (for each key pair), and it says that it's sending an email to all Used IDs. ..? Pretty sure each key pair only has one User ID.

Stand by while I check for new validation.. synchronization(?).. emails..

Ok, I received the verification/synchronization email in Outlook again. Here's what I discovered, The link is being decrypted on to multiple lines, and breaking it. so:
https://keys.mailvelope.com/api/v1/key?op=verify&keyId=blablabla
IS a link on one line and:
&nonce=moresillynonsense
is NOT part of the link on the second line. If I manually cut and paste both halves of the link, it succeeds.

It just occurred to me that that's probably GpgOL, not you guys. Let me know for sure, so I can pass the behavior on to them, ok?

Also, I did finally receive an email for the gmail key pair that I was trying to use mailvelope with in the first place. I don't know why I didn't receive the email the first time, but it worked manually, and the link was properly formed and it successfully verified. :)

**Comment by crogonint** [comment]
I don't know why the system made that one sentence huge. Did I accidentally type in some phpbb formatting code or something??

**Comment by toberndo** [comment]
> Ok, I received the verification/synchronization email in Outlook again. Here's what I discovered, The link is being decrypted on to multiple lines, and breaking it. so:
> https://keys.mailvelope.com/api/v1/key?op=verify&keyId=04a20b2164f08b79
> IS a link on one line and:
> &nonce=24be23f6092bf9a5be67827d484fa65c

This sounds like an issue with the link detection of GpgOL. The URL from the key server does not contain line breaks.

**Comment by crogonint** [comment]
Um.. I'm pretty sure that the verification email is recieved before GPG encryption is enabled.

No skin off my back, it's your end users that won't be able to use your product if you don't get it sorted. I figured out the problem myself. Most people probably won't know what to look for.
