### ISSUE TITLE
Sending key failed code = 58 gpg keyserver send failed: No data

### ISSUE THREAD

**Issue by iPPLE** [mailvelope/keyserver#108]
I'm using gpgtools on mac and point to my own server via hkps://xxxxx
the server is connected properly can lookup certificate, but when "Send Public key to server" i have this error:
But the email was sent and i was able to verify the public key successfully!.

Please kindly help to solve that error message.

**Comment by heylix** [comment]
Same here, only that I didn't get the mail to verify. Is that because I already have a key on the server and I have to delete it instead of replacing?

**Comment by tacerus** [comment]
@heylix I think it tries to replace the existing key for you if you try to upload one that already exists.

**Comment by toberndo** [comment]
This is the same issue as in https://github.com/mailvelope/keyserver/issues/98#issuecomment-1807100055 and is fixed now.
