### ISSUE TITLE
Public Key Installs

### ISSUE THREAD

**Issue by dms2015** [mailvelope/keyserver#122]
I was given three .pub files.  I figure one has the other two chained.  I am using a Linux system that I need to import these keys into for communication with an SFTP client.  Can someone help me with this?

The software I am using also on that server has the Java keytool command, but it looks like it is only taking .cer files.  However, I am unsure if I should be converting this file or putting it in the .ssh directory instead on Linux.

Here are the softwares instructions below...  It doesn't work - nor do I know which directory to place the file for this command.
**To add a public SSL certificate**
1 Open the console and go to the folder that contains the keytool utility
keytool.exe. The command to do this is:
cd app4.0\jre\bin
2 Use this command to import a public SSL key from a trading partner into a
trusted keystore that comes with the BizManager installation. For example:
keytool -import -alias TP1 -file TP1key.cer -keystore ..\..\protectedstore\trusted.jks -storepass <password>
Note: In the example, TP1 is the alias for the public key TP1.cer.
3 Allow keytool to place a "trusted certificate" entry into the trusted.jks keystore.
In this example, the entry contains the public key certificate data from the file
TP1key.cer, and assigns the alias TP1 to the entry.

It has been a while since I have logged into GITHub, so I hope I am putting out my question correctly.

**Comment by tacerus** [comment]
Hi,

I think you got the wrong repository - this repository is about the Mailvelope Keyserver, a program which is not related to SFTP or the Java `keytool`.
