### ISSUE TITLE
are you still alive?

### ISSUE THREAD

**Issue by strausmann** [mailvelope/keyserver#135]
Is this project still alive? nothing has happened here for almost three quarters of a year. 

In addition, nothing happens when searching (OpenPGP key lookup) on https://keys.mailvelope.com/manage.html

**Comment by toberndo** [comment]
Alive and also online: https://keys.mailvelope.com/pks/lookup?op=get&search=info%40mailvelope.com

**Comment by jaschaurbach** [comment]
@toberndo Are you actively ignoring the issues and pull requests or is just "we have it running and do not care any more"?

**Comment by toberndo** [comment]
We are planning a major update later this year. So pull requests at the moment get not enough attention. Sorry!
