### ISSUE TITLE
No mail sent to verify updated key

### ISSUE THREAD

**Issue by metal3d** [mailvelope/keyserver#137]
Hi,
I updated my key that was expired, and a popup said that a mail was sent to verify. But nothing...

That worked when I remove a key, the problem is only when we upload a new key.

**Comment by metal3d** [comment]
To be sure, this is what appears on the keystore page:

![image](https://user-images.githubusercontent.com/100080/232783793-6d8626fa-eff0-4423-8bf4-063314e945ba.png)

I tried to press "resend" but nothing is received – One more time, if I remove the key, I receive a mail to confirm the removal.

**Comment by systemplatine** [comment]
Thanks for the details. We're checking this currently. As a possible workaround: You could try to upload manually here: https://keys.mailvelope.com/manage.html <https://keys.mailvelope.com/manage.html>
Please tell if this works.

**Comment by metal3d** [comment]
Is this OK with private keys ?

The problem is when I send the private key... the website you mention only mention public key

**Comment by systemplatine** [comment]
No. Never upload a private key. Keyserver is for exchanging public keys only. https://mailvelope.com/en/faq#sharing_keys

**Comment by metal3d** [comment]
The problem is when I want to use my own private key in the Mailvelop extension to sign / crypt messages. In this interface, it says that my keys are not sync.
Pressing the Sync button should send me a mail to confirm the addition.

**Comment by metal3d** [comment]
Oh, OK... the sync is made for public keys.

But that fails too:
![image](https://user-images.githubusercontent.com/100080/232792162-5b7c7b32-8405-429e-bbfa-2854d7a24ada.png)


Question: why cannot we use `gpg --send-keys` to mailvelop

**Comment by Cinorid** [comment]
same for me

**Comment by toberndo** [comment]
> Oh, OK... the sync is made for public keys.
> 
> But that fails too: ![image](https://user-images.githubusercontent.com/100080/232792162-5b7c7b32-8405-429e-bbfa-2854d7a24ada.png)
> 
> Question: why cannot we use `gpg --send-keys` to mailvelop

Could you please send the public key for further analysis?

**Comment by toberndo** [comment]
Can you please upload the key directly to https://keys.mailvelope.com/manage.html and see if you get an error message?
