### ISSUE TITLE
https://keys.mailvelope.com is detected as down

### ISSUE THREAD

**Issue by peteryagami** [mailvelope/keyserver#24]
![image](https://cloud.githubusercontent.com/assets/9047253/23597949/a6005158-01fc-11e7-9e61-6561853ef66f.png)

Using my own instance of mailvelope's keyserver I ran into this error, checking and trying to add "https://keys.mailvelope.com" as keyserver in the firefox and chrome extension I found the same error so I think this is could be a problem with the implementation of hkp protocol?

thanks for the good work!

**Comment by shuffle2** [comment]
It works fine here... :)

**Comment by peteryagami** [comment]
It's fixed now, I think this was more an issue of the plugin that of the keyserver.
Thanks
