### ISSUE TITLE
failure when uploading key

### ISSUE THREAD

**Issue by mdik** [mailvelope/keyserver#27]
Hi,

after upload of key `6E0A 4E90 3241 34F0 2788  445D 044A 25F5 267D C236` the keyserver threw an error message that went something like "email could not be sent", reducing the key via `gpg --armor --export-options export-minimal --export 6E0A4E90324134F02788445D044A25F5267DC236` resolved the issue.

My best guess would be that the issue is due to the attached photo user id, but it might be something else as reproduction with a random other key with photo id failed.

Sorry for vague error report. I will put better details when I set up my own mailvelope keyserver. But maybe this already helps to find the issue?

Sincerely,

Malte

**Comment by mdik** [comment]
A key with photo id that  can be uploaded without error would be e.g.
394651B0A7A577C3E656DECD1E0280E6282CB9E9

**Comment by shuffle2** [comment]
I just tried this on my own server (blocked email from being sent), the upload seemed to work fine. I used the pubkey from https://keybase.io/fabionatali . Maybe you should try again? :)  
btw, if I try to upload it to keys.mailvelope.com , then it says key already exists. Meaning it was uploaded successfully and the email was acknowledged by the owner.  
So...another invalid issue, looks like.

**Comment by mdik** [comment]
Ok. Sorry for the bother, and thank you for triaging!
