### ISSUE TITLE
Allow lookup by key "name" value

### ISSUE THREAD

**Issue by bnvk** [mailvelope/keyserver#3]
It's really helpful to users to be able to lookup keys by name as well as email field!

**Comment by tanx** [comment]
Hey @bnvk! The server is designed to allow for an automatic key lookup UX, which requires a unique ID e.g. email addres or key ID to work reliably. That's also why we don't allow short key IDs.

**Comment by bnvk** [comment]
@tanx ah interesting. Thanks for responding. I'm curious from an engineering perspective about what makes *non-unique* text searches "unreliable" is that something to do with MongoDB indexes, or lacktherof?

**Comment by tanx** [comment]
Well, the server can verify that I own `bob@example.com` and the private key with key ID `xyz` by sending an encrypted verification mail. This allows Mailvelope to automatically fetch the recipient public key when entering their email address in the editor. It can't verify that I am the only `Bob`.
