### ISSUE TITLE
Key Server Issues

### ISSUE THREAD

**Issue by derhornspieler** [mailvelope/keyserver#4]
Hello,

When I am trying to add my companies internal key server, it does not allow for a port to be added at the end of the address using a : . This pretty much makes the app useless for enterprise type environments wanting to test out your application addon.

When can we expect a fix?

**Comment by shuffle2** [comment]
Look at https://github.com/mailvelope/keyserver/blob/master/config/default.js for config example.
So, just add this to your in-use config:
```javascript
server: {
    port: 9999 // or whatever port you want
},
```

**Comment by toberndo** [comment]
With v4 of the key server the port would be defined as environment variable or in an `.env` file with:
```
PORT=3000
```
