### ISSUE TITLE
Talking with GnuPG to keyserver

### ISSUE THREAD

**Issue by GupTk** [mailvelope/keyserver#66]
Perhaps I am stupid or this is a GnuPG issue:
As the keyserver should be HKP compatible, it should be possible to query a key with GnuPG.
Using GnuGP 2.2.5 I tried many variations of the command line (with hkp://, with https://, without prefix, with port, with no port, ...). 
But I cannot get any key result.

Is it my fault or a GnuPG issue.

If it is my fault, please provide a command line for use with GnuPG.

Thanks

**Comment by mdik** [comment]
I have the same problem, and `gpg` itself doesn't give any helpful feedback.

The only thing I could figure out so far is, that the server does not respond if you connect to it via
```bash
openssl s_client -connect keys.mailvelope.com:443
```
and then try to get anything manually, like
```
GET /pks/lookup?op=get&search=0xabcdeeee HTTP/1.1
```
while e.g. curl and wget work.

So maybe it's how dirmngr is phrasing the request, and maybe some ddos or spam protection on the side of keys.mailvelope.com that are not compatible?

**Comment by dkg** [comment]
please try:

    gpg --keyserver hkps://keys.mailvelope.com --search  foo@example.com

This works fine for me here, with GnuPG 2.2.15.
