### ISSUE TITLE
Synchronization of keys?

### ISSUE THREAD

**Issue by RoPe93** [mailvelope/keyserver#74]
I haven't found anything on this topic. So is it possible to sync. keys from other keyserver with my instance of Mailvelope keyserver?
If not why?
If yes how?
Thanks.

**Comment by dkg** [comment]
if you're asking about [SKS-style synchronization](https://bitbucket.org/skskeyserver/sks-keyserver/wiki/Home), that appears to be deliberately out of scope for the mailvelope keyserver.  The mailvelope keyserver is a validating keyserver, and synchronizing from another keyserver would imply accepting the validation decisions of the other keyserver, which changes the semantics of the internal data model significantly.
