### ISSUE TITLE
Problem using private server to import key

### ISSUE THREAD

**Issue by rclabs-dev** [mailvelope/keyserver#79]
Hello dear team,

I've implemented Mailvelope Key Server from github on my private network and I'm using it together Mailvelope for Firefox (as a convention, whenever I quote Firefox, it should be interpreted as Mailvelope in Firefox; in addition, the key server configured and saved is my private server). So I'm having some problems. I thank you for some help:

First doubt is: I defined as a key server in Firefox, my private server. Also, I have exported to the key server some public keys to make tests. The problem is that when I'm going to import the server key using Firefox, this process does not work correctly (I think) because the server does not return a complete public key block; the server returns only the block like below:

information: 1: 1
Pub: 8A9B02981524A29C09585570B1EC5D10B5D256F8: 1: 2048: 1549892665 ::
uid: Regivaldo% 20G.% 20Costa% 20% 3Crcosta% 40rclabs.com.br% 3E :::

Next one is: using text encryption in Firefox, when I add a recipient stored on the key server, the public key is not found. I have monitored the server communication using tcpdump, but in no time, the Firefox package arrives. But even set the key as my private server, Firefox always does query to keys.mailvelope.com, never to my private server (except when I'm using the "Key Management -> Import Key" option and result is wrong like above.

Last one is: how I put the server to work using HTTPS. The only port listed when the server is started is the default, that is, the only port in listen is the 8888). I'm using the configuration shown in github, of course using my environment settings.

Thanks in advance for any help.

Kind regards.

Regivaldo Costa

**Comment by rclabs-dev** [comment]
Anyone to help me? 

Many thanks!

**Comment by toberndo** [comment]
@rclabs-dev what you see in the Mailvelope settings as "HKP key server" configuration only affects the key server that is used in the key management UI for the key search feature. Automatic key discovery for example in the Mailvelope editor always uses hard-wired the Mailvelope key server. We don't have a setting to use a custom key server here at the moment.

**Comment by rclabs-dev** [comment]
Hi dear, thanks for your reply.

It's ok! I hope which this feature come in any other future version of the mailvelope for browsers.

Many thanks.

Cheers!

Regivaldo Costa
--

**Comment by toberndo** [comment]
Mailvelope currently does not support custom key server search, but this issue belongs to the mailvelope/mailvelope repo. Missing HTTPS support is tracked in https://github.com/mailvelope/keyserver/issues/29
