### ISSUE TITLE
HKP search should accept e-mail addresses within angle-brackets

### ISSUE THREAD

**Issue by dkg** [mailvelope/keyserver#84]
`gpg(1)` says:

       --search-keys names
              Search  the  keyserver for the given names. Multiple names given
              here will be joined together to create the search string for the
              keyserver.   Option --keyserver must be used to give the name of
              this keyserver.  Keyservers that support different search  meth‐
              ods  allow  using the syntax specified in "How to specify a user
              ID" below.
[…]
    HOW TO SPECIFY A USER ID
[…]
       By exact match on an email address.
              This is indicated by enclosing the email address  in  the  usual
              way with left and right angles.

         <heinrichh@uni-duesseldorf.de>

This suggests that users and scripts are likely to search keyservers for an e-mail address specifically by wrapping it in angle brackets.

However, the HKPS interface implemented by the mailvelope keyserver returns `HTTP/1.1 501 Not Implemented` when the `search=` query parameter is wrapped in angle-brackets.

Instead, it should accept searches wrapped in angle brackets and treat them the same as it would a comparable search that is not wrapped in angle brackets.

**Comment by dkg** [comment]
This doesn't seem to have been fixed, but there's also no feedback on why not.  Could someone take a look at this and at least explain if this is desired behavior?

**Comment by toberndo** [comment]
Support for email addresses wrapped in angle-brackets is now implemented with https://github.com/mailvelope/keyserver/commit/f8011609e680767a206ceeb84799bffd9bec17c4
