### ISSUE TITLE
keys hosted on keyserver are subject to flooding attack

### ISSUE THREAD

**Issue by dkg** [mailvelope/keyserver#85]
It's possible to attach arbitrary third-party certifications to an already-validated OpenPGP certificates that are published on hkps://keys.mailvelope.com simply by uploading the augmented certificate to the "Manage Keys" web form.  Some OpenPGP keyserver clients will reject too-large certificates when fetched from a keyserver.

This means that an anonymous user can attach garbage to an OpenPGP certificate, potentially bloating it in size beyond what clients will accept.  If there is a limit to the quantity of third party certifications attachable to any given certificate, then the anonymous user can fill that limit, obstructing anyone else from attaching certifications.

This is a similar attack to one of the attacks that have been mounted against certificates hosted by the SKS keyserver network.

To fix the problem robustly, you'll either need to stop accepting third-party certifications entirely, or figure out some authorization scheme about which third-party certifications are acceptable for any given certificate.  I'm happy to demonstrate the attack for any of the Mailvelope developers privately, and to talk over the options for mitigation of the issue.

sorry to be the bearer of bad news!

**Comment by dkg** [comment]
One possible mitigation is to only accept [first-party attested third-party certifications](https://tools.ietf.org/html/draft-dkg-openpgp-abuse-resistant-keystore-00#section-6).  (i wrote the linked draft after some discussion with other interested folks earlier today -- feel free to suggest improvements if you think it's off-base)

**Comment by toberndo** [comment]
Added a tool to clean existing keys in the database with the filtering method described above: https://github.com/mailvelope/keyserver/commit/677656b4c13d9ad982cca9bcecfd4d73bc80905f
All keys on keys.mailvelope.com have been filtered in this way now.
