### ISSUE TITLE
Howto deploy in a selfhosted scenario

### ISSUE THREAD

**Issue by dartmann** [mailvelope/keyserver#86]
Hi there,
maybe a little howto section for the steps to take when someone wants to host this nice piece of software on e.g. an Apache would be cool. Especially when the person is not that familiar with Javascript build/dependency mgmt. tools like npm.
Kind regards, David

**Comment by nsauter** [comment]
You still need help?

**Comment by dartmann** [comment]
Hi @nsauter, no I got it running some days after my post. But anyway, wouldn't it be helpful for others to see a minimal example of howto set it up?

**Comment by nsauter** [comment]
Absolutely, i had the same problem at first. What about cloning the git and adding something in the readme?

How you managed to get the development.js/production.js working? That was the only thing i did not find out. I just exported those settings as environment variables...

**Comment by dartmann** [comment]
Yes, that would be a compromise. I was hoping that the maintainers would add this to the official repo...

If I remember correctly, I did the same. Unfortunately, I do not have access to the src of that project now.

**Comment by stradarius** [comment]
See my pull request #118 with changes for README.md. This should (hopefully) explain the part about development/production.
