### ISSUE TITLE
"Not Implemented" when searching mail domain

### ISSUE THREAD

**Issue by variablenix** [mailvelope/keyserver#89]
Hi,

This might be more of a feature request, but I noticed mailvelope keyserver does not return results when searching just the mail domain. If you search for _gmail.com_ or any mail domain within the _OpenPGP key lookup_ field, you get **Not Implemented**. I tried playing around with the mailvelope API, but got the same results. It would be great if searching by mail domain was implemented like SKS. Thanks for developing such a nice and modernized keyserver.

**Comment by toberndo** [comment]
Search by domain or with a wildcard would allow email harvesting. As we want to protect the identity of the users we do not intend to implement this feature.

**Comment by variablenix** [comment]
Got it. Makes sense. Thanks for clarifying about this.
