### ISSUE TITLE
Use config/ to define the server host

### ISSUE THREAD

**Issue by yzaguirre** [mailvelope/keyserver#9]
I don't know if its possible to setup **https** within the project but I'm doing it through Apache2 proxy. It works fine until the emails sent have the wrong link.

The verification and removal link that arrives vía email always says:
`http://localhost:8888`
but the ideal link should be
`https://keys.mydomain`
Can you make the **host** or **baseUrl** configurable in config/ directory?

**Comment by shuffle2** [comment]
This is done, in config just add:
```javascript
origin: {
  protocol: "https",
  host: "<your_host_name>"
},
```
Issue should be closed.
