### ISSUE TITLE
can't 'Upload Public Keys to Keyserver' from t'bird-enigmail

### ISSUE THREAD

**Issue by xpseudonym** [mailvelope/keyserver#93]
can't 'Upload Public Keys to Keyserver' from Enigmail
I get the response:
'Sending of keys failed'
Enigmail version 2.0.8 (20190203-0951)

**Comment by toberndo** [comment]
Would need to retest this in Thunderbird to see how the situation is now.

**Comment by toberndo** [comment]
Probably same issue as in https://github.com/mailvelope/keyserver/issues/98#issuecomment-1807100055 and should be fixed now.
